#site settings
title: Emily Baron
email: emilybaron3@gmail.com
url: embaron.github.io
github_user: embaron

greeting: Hello

#build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title

number_of_items_in_row: 3
